//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onion.Demo.Client.FiscalService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FiscalService.FiscalService")]
    public interface FiscalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FiscalService/CalculateAllTax", ReplyAction="http://tempuri.org/FiscalService/CalculateAllTaxResponse")]
        double CalculateAllTax();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FiscalServiceChannel : Onion.Demo.Client.FiscalService.FiscalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FiscalServiceClient : System.ServiceModel.ClientBase<Onion.Demo.Client.FiscalService.FiscalService>, Onion.Demo.Client.FiscalService.FiscalService {
        
        public FiscalServiceClient() {
        }
        
        public FiscalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FiscalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FiscalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FiscalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double CalculateAllTax() {
            return base.Channel.CalculateAllTax();
        }
    }
}
